#!/usr/bin/env python3
"""Compiles an HTML page to preview the banners and animated badge generated by the image generator."""

from pathlib import Path

ROOT = Path("/Users/cc/Desktop/photo_show")
OUT = ROOT / "output/emag_banner_generation_tests"

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    
    html_content = """<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <title>EXCITAT - Generated Banners & Brand Icon Gallery</title>
  <style>
    body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; padding: 40px 20px; }
    main { max-width: 1200px; margin: 0 auto; }
    header { text-align: center; margin-bottom: 50px; }
    h1 { font-size: 36px; color: #ffffff; margin-bottom: 12px; font-weight: 800; letter-spacing: -0.5px; }
    header p { color: #94a3b8; font-size: 18px; margin: 0; }
    .section { background: #1e293b; border-radius: 16px; border: 1px solid #334155; padding: 32px; margin-bottom: 40px; }
    h2 { font-size: 24px; color: #00e5ff; margin-top: 0; margin-bottom: 8px; font-weight: 700; }
    .desc { color: #94a3b8; font-size: 15px; margin-bottom: 24px; line-height: 1.5; }
    .banner-container { margin-bottom: 30px; }
    img.banner { width: 100%; height: auto; border-radius: 12px; border: 2px solid #334155; box-shadow: 0 4px 20px rgba(0,0,0,0.2); }
    .badge-container { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 20px; background: #0f172a; border-radius: 12px; border: 1px solid #334155; width: fit-content; margin: 0 auto; }
    img.badge { width: 240px; height: 240px; border-radius: 8px; }
    .badge-title { font-weight: 700; margin-top: 14px; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #00e5ff; }
  </style>
</head>
<body>
  <main>
    <header>
      <h1>EXCITAT Premium Generated Assets</h1>
      <p>Banners and animated brand elements generated directly using the "Template + Prompt" image generator workflow.</p>
    </header>
    
    <div class="section">
      <h2>1. Glassmorphism Neon Style Banner</h2>
      <div class="desc">A sleek EV cable banner featuring rounded frosted glass layers and cyan glowing neon circles.</div>
      <div class="banner-container">
        <img class="banner" src="generator_banner_glassmorphism.jpg" alt="Glassmorphism Neon Banner">
      </div>
    </div>
    
    <div class="section">
      <h2>2. Premium Dark Technical Banner</h2>
      <div class="desc">An industrial dark carbon fiber grid background with sharp gold line accents and connectors.</div>
      <div class="banner-container">
        <img class="banner" src="generator_banner_premium_dark.jpg" alt="Premium Dark Banner">
      </div>
    </div>
    
    <div class="section">
      <h2>3. Organic Lifestyle Wood & Stone Banner</h2>
      <div class="desc">A minimalist design blending travertine marble and natural oak wood paneling with leaf shadows.</div>
      <div class="banner-container">
        <img class="banner" src="generator_banner_organic_wood.jpg" alt="Organic Wood Banner">
      </div>
    </div>
    
    <div class="section">
      <h2>4. Animated Brand Badge Icon</h2>
      <div class="desc">A 3D glass logo tag with breathing neon cyan back-glow and outer border pulse.</div>
      <div class="badge-container">
        <img class="badge" src="../emag_motion_effect_demos/brand_icon_glow_ai_generated.gif" alt="Animated EXCITAT Brand Badge">
        <div class="badge-title">brand_icon_glow_ai_generated.gif</div>
      </div>
    </div>
    
  </main>
</body>
</html>
"""
    
    output_file = OUT / "banners_preview_generation.html"
    output_file.write_text(html_content, encoding="utf-8")
    print(f"✓ Generated preview HTML file: {output_file.name}")

if __name__ == "__main__":
    main()
